In [21]:

# Imports
import numpy as np
import pandas as pd 
from scipy import stats

# Leitura do arquivo .csv por meio da biblioteca pandas
students_df = pd.read_csv("predict_students_dropout_and_academic_success.csv", sep = ";")
students_df.columns = students_df.columns.str.strip()

In [10]:

# Drop da coluna alvo para manipulação do dataframe
y = students_df["Target"];
students_df.drop("Target", axis = 1, errors = "ignore", inplace = True)

In [19]:
# 1. Medidas de Tendência Central
def medidas_tendencia_central(students_df, column):
    series = students_df[column]
    media = series.mean()
    mediana = series.median()  # Funciona para qualquer tamanho de DF!
    ponto_medio = (series.max() + series.min()) / 2
    moda = series.mode()[0]

    return {
        "Media": media,
        "Mediana": mediana,
        "Ponto Medio": ponto_medio,
        "Moda": moda,
    }


# 2. Medidas de Dispersão
def medidas_dispersao(students_df, column):
    series = students_df[column]
    amplitude = series.max() - series.min()
    variancia = series.var(ddof=0)
    desvio_padrao = series.std(ddof=0)
    coef_variacao = (desvio_padrao / media) * 100 if "media" in locals() else (desvio_padrao / series.mean()) * 100

    return {
        "Amplitude": amplitude,
        "Variancia": variancia,
        "Desvio Padrao": desvio_padrao,
        "Coef. Variacao": coef_variacao,
    }


# 3. Medidas de Posição Relativa
def medidas_posicao_relativa(students_df, column):
    series = students_df[column]
    score_z = stats.zscore(series)
    quartil1 = series.quantile(0.25)
    quartil2 = series.quantile(0.50)
    quartil3 = series.quantile(0.75)
    amplitude_quartil = quartil3 - quartil1

    return {
        "Menor Score-Z": score_z.min(),
        "Maior Score-Z": score_z.max(),
        "Quartil 1": quartil1,
        "Quartil 2": quartil2,
        "Quartil 3": quartil3,
        "Amplitude Interquartil": amplitude_quartil,
    }


# 4. Medidas de Associação
def medidas_associacao(students_df, column1, column2):
    covariancia = np.cov(students_df[column1], students_df[column2], ddof=0)[
        0, 1
    ]
    correlacao = students_df[column1].corr(students_df[column2])
    print(f"Covariância entre {column1} e {column2}: {covariancia:.4f}")
    print(f"Correlação entre {column1} e {column2}: {correlacao:.4f}")

In [12]:

# Separação das colunas Categóricas das colunas Numéricas
colunas_categoricas = [
    'Marital status',                 # Estado Civil
    'Application mode',               # Modo de Ingresso na Instituição
    'Application order',              # Ordem de Aplicação (1a escolha, 2a, 3a, ...)
    'Course',                         # Curso 
    'Daytime/evening attendance',     # Período de estudos (diurno/noturno)
    'Previous qualification',         # Qualificação prévia
    'Nacionality',                    # Nacionalidade
    "Mother's qualification",         # Qualificação da Mãe
    "Father's qualification",         # Qualificação do Pai
    "Mother's occupation",            # Ocupação da Mãe
    "Father's occupation",            # Ocupação do Pai
    'Displaced',                      # Deslocado (se precisou se mudar)
    'Educational special needs',      # Necessidades Educacionais Especiais
    'Debtor',                         # Devedor 
    'Tuition fees up to date',        # Mensalidades em Dia
    'Gender',                         # Gênero
    'Scholarship holder',             # Bolsista
    'International',                  # Internacional
]

colunas_numericas = [
    'Previous qualification (grade)',                       # Qualificação anterior (nota)
    'Admission grade',                                      # Nota de admissão
    'Age at enrollment',                                    # Idade de matrícula
    'Curricular units 1st sem (credited)',                  # Unidades curriculares 1o semestre (creditadas aproveitamento)
    'Curricular units 1st sem (enrolled)',                  # Unidades curriculares 1o semestre (matriculadas)
    'Curricular units 1st sem (evaluations)',               # Unidades curriculares 1o semestre (avaliações aplicadas)
    'Curricular units 1st sem (approved)',                  # Unidades curriculares 1o semestre (aprovadas)
    'Curricular units 1st sem (grade)',                     # Unidades curriculares 1o semestre (nota)
    'Curricular units 1st sem (without evaluations)',       # Unidades curriculares 1o semestre (sem avaliações)
    'Curricular units 2nd sem (credited)',                  # Unidades curriculares 2o semestre (creditadas aproveitamento)
    'Curricular units 2nd sem (enrolled)',                  # Unidades curriculares 2o semestre (matriculadas)
    'Curricular units 2nd sem (evaluations)',               # Unidades curriculares 2o semestre (avaliações aplicadas)
    'Curricular units 2nd sem (approved)',                  # Unidades curriculares 2o semestre (aprovadas)
    'Curricular units 2nd sem (grade)',                     # Unidades curriculares 2o semestre (nota)
    'Curricular units 2nd sem (without evaluations)',       # Unidades curriculares 2o semestre (sem avaliações)
    'Unemployment rate',                                    # Indice desemprego
    'Inflation rate',                                       # Indice de inflação
    'GDP'                                                   # PIB 
]

In [23]:

# Cálculo das medidas de resumo para as colunas numéricas
resultados_colunas = []

for column in colunas_numericas:
    resumo_coluna = {"Coluna": column}
    resumo_coluna.update(medidas_tendencia_central(students_df, column))
    resumo_coluna.update(medidas_dispersao(students_df, column))
    resumo_coluna.update(medidas_posicao_relativa(students_df, column))

    resultados_colunas.append(resumo_coluna)

# Resultados em um df para análise
df_resumo_estatistico = pd.DataFrame(resultados_colunas)
df_resumo_estatistico = df_resumo_estatistico.round(4)
df_resumo_estatistico

,Coluna,Media,Mediana,Ponto Medio,Moda,Amplitude,Variancia,Desvio Padrao,Coef. Variacao,Menor Score-Z,Maior Score-Z,Quartil 1,Quartil 2,Quartil 3,Amplitude Interquartil
0,Previous qualification (grade),132.6133,133.1000,142.5000,133.10,95.0000,173.8928,13.1868,9.9438,-2.8523,4.3518,125.00,133.1000,140.0000,15.0000
1,Admission grade,126.9781,126.1000,142.5000,130.00,95.0000,209.6809,14.4804,11.4038,-2.2084,4.3522,117.90,126.1000,134.8000,16.9000
2,Age at enrollment,23.2651,20.0000,43.5000,18.00,53.0000,57.5619,7.5870,32.6108,-0.8258,6.1599,19.00,20.0000,25.0000,6.0000
3,Curricular units 1st sem (credited),0.7100,0.0000,10.0000,0.00,20.0000,5.5707,2.3602,332.4324,-0.3008,8.1729,0.00,0.0000,0.0000,0.0000
4,Curricular units 1st sem (enrolled),6.2706,6.0000,13.0000,6.00,26.0000,6.1499,2.4799,39.5482,-2.5286,7.9557,5.00,6.0000,7.0000,2.0000
5,Curricular units 1st sem (evaluations),8.2991,8.0000,22.5000,8.00,45.0000,17.4610,4.1786,50.3507,-1.9861,8.7830,6.00,8.0000,10.0000,4.0000
6,Curricular units 1st sem (approved),4.7066,5.0000,13.0000,6.00,26.0000,9.5721,3.0939,65.7351,-1.5213,6.8824,3.00,5.0000,6.0000,3.0000
7,Curricular units 1st sem (grade),10.6408,12.2857,9.4375,0.00,18.8750,23.4558,4.8431,45.5145,-2.1971,1.7002,11.00,12.2857,13.4000,2.4000
8,Curricular units 1st sem (without evaluations),0.1377,0.0000,6.0000,0.00,12.0000,0.4772,0.6908,501.8241,-0.1993,17.1718,0.00,0.0000,0.0000,0.0000
9,Curricular units 2nd sem (credited),0.5418,0.0000,9.5000,0.00,19.0000,3.6800,1.9183,354.0546,-0.2824,9.6220,0.00,0.0000,0.0000,0.0000
10,Curricular units 2nd sem (enrolled),6.2321,6.0000,11.5000,6.00,23.0000,4.8211,2.1957,35.2319,-2.8383,7.6367,5.00,6.0000,7.0000,2.0000
11,Curricular units 2nd sem (evaluations),8.0633,8.0000,16.5000,8.00,33.0000,15.5828,3.9475,48.9565,-2.0426,6.3171,6.00,8.0000,10.0000,4.0000
12,Curricular units 2nd sem (approved),4.4358,5.0000,10.0000,6.00,20.0000,9.0867,3.0144,67.9566,-1.4715,5.1632,2.00,5.0000,6.0000,4.0000
13,Curricular units 2nd sem (grade),10.2302,12.2000,9.2857,0.00,18.5714,27.1464,5.2102,50.9298,-1.9635,1.6009,10.75,12.2000,13.3333,2.5833
14,Curricular units 2nd sem (without evaluations),0.1503,0.0000,6.0000,0.00,12.0000,0.5680,0.7537,501.4014,-0.1994,15.7222,0.00,0.0000,0.0000,0.0000
15,Unemployment rate,11.5661,11.1000,11.9000,7.60,8.6000,7.0945,2.6635,23.0289,-1.4890,1.7397,9.40,11.1000,13.9000,4.5000
16,Inflation rate,1.2280,1.4000,1.4500,1.40,4.5000,1.9115,1.3826,112.5832,-1.4669,1.7880,0.30,1.4000,2.6000,2.3000
17,GDP,0.0020,0.3200,-0.2750,0.32,7.5700,5.1514,2.2697,115281.9674,-1.7897,1.5456,-1.70,0.3200,1.7900,3.4900

In [24]:
# Cálculo da moda para as colunas categóricas
resultados_colunas_2 = []

for column in colunas_categoricas:
    # Chamando a função apenas UMA vez
    moda = calculo_moda(students_df, column)
    numero_categorias = students_df[column].nunique()

    resumo_coluna = {
        "Coluna": column,
        "Número categorias": numero_categorias,
        "Moda": moda,
    }

    resultados_colunas_2.append(resumo_coluna)

# Resultado das modas em um df separado para análise
df_resumo_categoricas = pd.DataFrame(resultados_colunas_2)

# Lista com as categorias originais das modas
Categoria = [
    "Single",
    "1st phase - general contingent",
    "first choice",
    "Nursing",
    "daytime",
    "Secondary education",
    "Portuguese",
    "Secondary Education - 12th Year of Schooling or Eq.",
    "Basic education 1st cycle (4th/5th year) or equiv.",
    "Unskilled Workers",
    "Unskilled Workers",
    "yes",
    "no",
    "no",
    "yes",
    "female",
    "no",
    "no",
]

# Adicionando a coluna ao D resultante
df_resumo_categoricas["Categoria"] = Categoria

In [25]:

# Visualização do valor de moda e da categoria atribuida
df_resumo_categoricas

,Coluna,Número categorias,Moda,Categoria
0,Marital status,6,1,Single
1,Application mode,18,1,1st phase - general contingent
2,Application order,8,1,first choice
3,Course,17,9500,Nursing
4,Daytime/evening attendance,2,1,daytime
5,Previous qualification,17,1,Secondary education
6,Nacionality,21,1,Portuguese
7,Mother's qualification,29,1,Secondary Education - 12th Year of Schooling o...
8,Father's qualification,34,37,Basic education 1st cycle (4th/5th year) or eq...
9,Mother's occupation,32,9,Unskilled Workers
10,Father's occupation,46,9,Unskilled Workers
11,Displaced,2,1,yes
12,Educational special needs,2,0,no
13,Debtor,2,0,no
14,Tuition fees up to date,2,1,yes
15,Gender,2,0,female
16,Scholarship holder,2,0,no
17,International,2,0,no